name: Release
on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name : Set outputs
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Release binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Release Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        with:
          name: insidersec/insider
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: GO_VERSION=1.15
          tags: "latest,${{ env.RELEASE_VERSION }}"
          tag_names: true
